---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: web
spec:
  prefix: /web/
  service: web-sidecar-proxy
  resolver: consul-west
  tls: ambassador-consul
  load_balancer:
    policy: round_robin