apiVersion: v1
kind: ServiceAccount
metadata:
  name: currency
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  labels:
    app: currency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      serviceAccountName: currency
      containers:
      - name: currency
        image: "nicholasjackson/fake-service:v0.7.8"
        imagePullPolicy: Always
        
        ports:
        - containerPort: 9094
        env:
          - name: LISTEN_ADDR
            value: "0.0.0.0:9094"
          - name: UPSTREAM_URIS
            value:
          - name: MESSAGE
            value: "Backend Currency Service running in west kubernetes"
          - name: NAME
            value: "currency"
          - name: SERVER_TYPE
            value: "http"
          # - name: ERROR_RATE
          #   value: "0.5"
          # - name: ERROR_CODE
          #   value: "500"
          # - name: ERROR_TYPE
          #   value: "http_error"
          - name: TRACING_ZIPKIN
            value: "http://jaeger-collector:9411"

      - name: prometheus-statsd
        image: "prom/statsd-exporter:latest"
        ports:
          - name: metrics
            containerPort: 9102
          - name: statsd
            containerPort: 9125
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
