apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "currency:9094"
    spec:
      serviceAccountName: payments
      containers:
      - name: payments
        image: "nicholasjackson/fake-service:v0.7.8"
        imagePullPolicy: Always
        
        ports:
        - containerPort: 9093
        env:
          - name: LISTEN_ADDR
            value: "0.0.0.0:9093"
          - name: UPSTREAM_URIS
            value: "http://127.0.0.1:9094"
          - name: MESSAGE
            value: "Payments response"
          - name: NAME
            value: "payments"
          - name: SERVER_TYPE
            value: "http"
          - name:  HTTP_CLIENT_REQUEST_TIMEOUT
            value: "10s"

      - name: prometheus-statsd
        image: "prom/statsd-exporter:latest"
        ports:
          - name: metrics
            containerPort: 9102
          - name: statsd
            containerPort: 9125
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
