server:
  global:
    scrape_interval: 10s
extraScrapeConfigs: |
  - job_name: 'sample-job'
    scrape_interval: 1s
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_pod_container_name]
        regex: "prometheus-statsd"
  - job_name: 'envoy-metrics'
    scrape_interval: 10s
    scrape_timeout: 5s	
    consul_sd_configs:
      - server: '10.0.1.100:8500'
        services: 	 
          - api
          - web
          - dashboard
          - counting 
    relabel_configs:
      - source_labels: [__address__]
        separator:     ':'
        regex:         '(.*):(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9102'